package/gstreamer1: fix static build break after change to meson build
Add upstream patch to work around meson bug with linking static
libraries, fixes [1]:

.../arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libgstreamer-1.0.a(gstelement.c.o): In function `_gst_element_error_printf':
gstelement.c:(.text+0x3fe8): undefined reference to `__gst_vasprintf'
.../arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libgstreamer-1.0.a(gstinfo.c.o): In function `gst_debug_message_get':
gstinfo.c:(.text+0x1df0): undefined reference to `__gst_vasprintf'
.../arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libgstreamer-1.0.a(gstinfo.c.o): In function `_priv_gst_debug_init':
gstinfo.c:(.text+0x34a4): undefined reference to `__gst_printf_pointer_extension_set_func'
.../arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libgstreamer-1.0.a(gstinfo.c.o): In function `gst_info_vasprintf':
gstinfo.c:(.text+0x40b4): undefined reference to `__gst_vasprintf'
collect2: error: ld returned 1 exit status

[1] http://autobuild.buildroot.net/results/9f92b180835df9ed580fe2420687a3632d08b3e4

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>